//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrain
    {
        public int TrainNo { get; set; }
        public string TrainName { get; set; }
        public string Departcher { get; set; }
        public string Destination { get; set; }
    }
}
